# Generated by Django 5.2.4 on 2025-08-05 07:02

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_field',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, scale=None, size=[800, 600], upload_to='post_images/'),
        ),
    ]
