# Generated by Django 5.2.4 on 2025-08-19 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_image_image_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('condition', models.CharField(choices=[('NW', 'New'), ('US', 'Used'), ('RF', 'Refurbished')], default='NW', max_length=2)),
                ('is_available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='blog.post')),
            ],
            options={
                'verbose_name': 'Post Detail',
                'verbose_name_plural': 'Post Details',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='image',
            name='post_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.postdetail', verbose_name='تصویر جزییات'),
        ),
        migrations.AddIndex(
            model_name='postdetail',
            index=models.Index(fields=['sku'], name='blog_postde_sku_667852_idx'),
        ),
        migrations.AddIndex(
            model_name='postdetail',
            index=models.Index(fields=['-created'], name='blog_postde_created_b868ba_idx'),
        ),
    ]
