# Generated by Django 5.2.4 on 2025-08-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postdetail_image_post_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdetail',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='postdetail',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان'),
        ),
    ]
